### ISSUE TITLE
TODO...

### ISSUE THREAD

**Issue by busticated** [busticated/dotfilez#1]
- [ ] install homebrew [setup.sh]
- [ ] setup ssh keys if unavailable [setup.sh]
- [ ] install default apps (macvim, postgres, rbenv, node, etc) via homebrew [setup.sh]
